// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// lcd_output //
// ---------- //

#define lcd_output_wrap_target 0
#define lcd_output_wrap 3

#define lcd_output_offset_tx16 0u
#define lcd_output_offset_tx8 2u

#if 1
static const uint16_t lcd_output_program_instructions[] = {
            //     .wrap_target
    0x7008, //  0: out    pins, 8         side 0     
    0x1800, //  1: jmp    0               side 1     
    0x7000, //  2: out    pins, 32        side 0     
    0x7878, //  3: out    null, 24        side 1     
            //     .wrap
};
#else
static const uint16_t lcd_output_program_instructions[] = {
            //     .wrap_target
    0x7008, //  0: out    pins, 8         side 0     
    0x1800, //  1: jmp    0               side 1     
    0x7008, //  2: out    pins, 8         side 0     
    0x7878, //  3: out    null, 24        side 1     
            //     .wrap
};
#endif

#if !PICO_NO_HARDWARE
static const struct pio_program lcd_output_program = {
    .instructions = lcd_output_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config lcd_output_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + lcd_output_wrap_target, offset + lcd_output_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}


#endif
